version: '3'

# Container services
services:
  samba:
    image: stephenneal/samba-efs:v2
    container_name: samba
    networks:
      - default
    environment:
      - USER1=stephen;stealth
      - USER2=harnaudo;patriots9
      - USER3=bob;patriots9
      - SHARE1=HPA;/efs;yes;no;no;
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139/tcp"
      - "445:445/tcp"
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - ./:/efs

# Network
networks:
  default:

# Volumes
volumes:
  efs: